import { SemitoneSpan } from '../SemitoneSpan';

describe('SemitoneSpan construction test', () => {

  test.each<{ totalSemitones: number, spannedOctaves: number }>([
    { totalSemitones: -50, spannedOctaves: -4 },
    { totalSemitones: -49, spannedOctaves: -4 },
    { totalSemitones: -48, spannedOctaves: -4 },
    { totalSemitones: -47, spannedOctaves: -3 },
    { totalSemitones: -46, spannedOctaves: -3 },
    { totalSemitones: -45, spannedOctaves: -3 },
    { totalSemitones: -44, spannedOctaves: -3 },
    { totalSemitones: -43, spannedOctaves: -3 },
    { totalSemitones: -42, spannedOctaves: -3 },
    { totalSemitones: -41, spannedOctaves: -3 },
    { totalSemitones: -40, spannedOctaves: -3 },
    { totalSemitones: -39, spannedOctaves: -3 },
    { totalSemitones: -38, spannedOctaves: -3 },
    { totalSemitones: -37, spannedOctaves: -3 },
    { totalSemitones: -36, spannedOctaves: -3 },
    { totalSemitones: -35, spannedOctaves: -2 },
    { totalSemitones: -34, spannedOctaves: -2 },
    { totalSemitones: -33, spannedOctaves: -2 },
    { totalSemitones: -32, spannedOctaves: -2 },
    { totalSemitones: -31, spannedOctaves: -2 },
    { totalSemitones: -30, spannedOctaves: -2 },
    { totalSemitones: -29, spannedOctaves: -2 },
    { totalSemitones: -28, spannedOctaves: -2 },
    { totalSemitones: -27, spannedOctaves: -2 },
    { totalSemitones: -26, spannedOctaves: -2 },
    { totalSemitones: -25, spannedOctaves: -2 },
    { totalSemitones: -24, spannedOctaves: -2 },
    { totalSemitones: -23, spannedOctaves: -1 },
    { totalSemitones: -22, spannedOctaves: -1 },
    { totalSemitones: -21, spannedOctaves: -1 },
    { totalSemitones: -20, spannedOctaves: -1 },
    { totalSemitones: -19, spannedOctaves: -1 },
    { totalSemitones: -18, spannedOctaves: -1 },
    { totalSemitones: -17, spannedOctaves: -1 },
    { totalSemitones: -16, spannedOctaves: -1 },
    { totalSemitones: -15, spannedOctaves: -1 },
    { totalSemitones: -14, spannedOctaves: -1 },
    { totalSemitones: -13, spannedOctaves: -1 },
    { totalSemitones: -12, spannedOctaves: -1 },
    { totalSemitones: -11, spannedOctaves: 0 },
    { totalSemitones: -10, spannedOctaves: 0 },
    { totalSemitones: -9, spannedOctaves: 0 },
    { totalSemitones: -8, spannedOctaves: 0 },
    { totalSemitones: -7, spannedOctaves: 0 },
    { totalSemitones: -6, spannedOctaves: 0 },
    { totalSemitones: -5, spannedOctaves: 0 },
    { totalSemitones: -4, spannedOctaves: 0 },
    { totalSemitones: -3, spannedOctaves: 0 },
    { totalSemitones: -2, spannedOctaves: 0 },
    { totalSemitones: -1, spannedOctaves: 0 },
    { totalSemitones: 0, spannedOctaves: 0 },
    { totalSemitones: 1, spannedOctaves: 0 },
    { totalSemitones: 2, spannedOctaves: 0 },
    { totalSemitones: 3, spannedOctaves: 0 },
    { totalSemitones: 4, spannedOctaves: 0 },
    { totalSemitones: 5, spannedOctaves: 0 },
    { totalSemitones: 6, spannedOctaves: 0 },
    { totalSemitones: 7, spannedOctaves: 0 },
    { totalSemitones: 8, spannedOctaves: 0 },
    { totalSemitones: 9, spannedOctaves: 0 },
    { totalSemitones: 10, spannedOctaves: 0 },
    { totalSemitones: 11, spannedOctaves: 0 },
    { totalSemitones: 12, spannedOctaves: 1 },
    { totalSemitones: 13, spannedOctaves: 1 },
    { totalSemitones: 14, spannedOctaves: 1 },
    { totalSemitones: 15, spannedOctaves: 1 },
    { totalSemitones: 16, spannedOctaves: 1 },
    { totalSemitones: 17, spannedOctaves: 1 },
    { totalSemitones: 18, spannedOctaves: 1 },
    { totalSemitones: 19, spannedOctaves: 1 },
    { totalSemitones: 20, spannedOctaves: 1 },
    { totalSemitones: 21, spannedOctaves: 1 },
    { totalSemitones: 22, spannedOctaves: 1 },
    { totalSemitones: 23, spannedOctaves: 1 },
    { totalSemitones: 24, spannedOctaves: 2 },
    { totalSemitones: 25, spannedOctaves: 2 },
    { totalSemitones: 26, spannedOctaves: 2 },
    { totalSemitones: 27, spannedOctaves: 2 },
    { totalSemitones: 28, spannedOctaves: 2 },
    { totalSemitones: 29, spannedOctaves: 2 },
    { totalSemitones: 30, spannedOctaves: 2 },
    { totalSemitones: 31, spannedOctaves: 2 },
    { totalSemitones: 32, spannedOctaves: 2 },
    { totalSemitones: 33, spannedOctaves: 2 },
    { totalSemitones: 34, spannedOctaves: 2 },
    { totalSemitones: 35, spannedOctaves: 2 },
    { totalSemitones: 36, spannedOctaves: 3 },
    { totalSemitones: 37, spannedOctaves: 3 },
    { totalSemitones: 38, spannedOctaves: 3 },
    { totalSemitones: 39, spannedOctaves: 3 },
    { totalSemitones: 40, spannedOctaves: 3 },
    { totalSemitones: 41, spannedOctaves: 3 },
    { totalSemitones: 42, spannedOctaves: 3 },
    { totalSemitones: 43, spannedOctaves: 3 },
    { totalSemitones: 44, spannedOctaves: 3 },
    { totalSemitones: 45, spannedOctaves: 3 },
    { totalSemitones: 46, spannedOctaves: 3 },
    { totalSemitones: 47, spannedOctaves: 3 },
    { totalSemitones: 48, spannedOctaves: 4 },
    { totalSemitones: 49, spannedOctaves: 4 },
    { totalSemitones: 50, spannedOctaves: 4 }

  ])(
    'A SemitoneSpan of $totalSemitones semitones should span $spannedOctaves octaves',
    d => expect((new SemitoneSpan(d.totalSemitones)).spannedOctaves).toBe(d.spannedOctaves)
  );

  test.each<{ totalSemitones: number, remaindingSemitones: number }>([
    { totalSemitones: -50, remaindingSemitones: -2 },
    { totalSemitones: -49, remaindingSemitones: -1 },
    { totalSemitones: -48, remaindingSemitones: 0 },
    { totalSemitones: -47, remaindingSemitones: -11 },
    { totalSemitones: -46, remaindingSemitones: -10 },
    { totalSemitones: -45, remaindingSemitones: -9 },
    { totalSemitones: -44, remaindingSemitones: -8 },
    { totalSemitones: -43, remaindingSemitones: -7 },
    { totalSemitones: -42, remaindingSemitones: -6 },
    { totalSemitones: -41, remaindingSemitones: -5 },
    { totalSemitones: -40, remaindingSemitones: -4 },
    { totalSemitones: -39, remaindingSemitones: -3 },
    { totalSemitones: -38, remaindingSemitones: -2 },
    { totalSemitones: -37, remaindingSemitones: -1 },
    { totalSemitones: -36, remaindingSemitones: 0 },
    { totalSemitones: -35, remaindingSemitones: -11 },
    { totalSemitones: -34, remaindingSemitones: -10 },
    { totalSemitones: -33, remaindingSemitones: -9 },
    { totalSemitones: -32, remaindingSemitones: -8 },
    { totalSemitones: -31, remaindingSemitones: -7 },
    { totalSemitones: -30, remaindingSemitones: -6 },
    { totalSemitones: -29, remaindingSemitones: -5 },
    { totalSemitones: -28, remaindingSemitones: -4 },
    { totalSemitones: -27, remaindingSemitones: -3 },
    { totalSemitones: -26, remaindingSemitones: -2 },
    { totalSemitones: -25, remaindingSemitones: -1 },
    { totalSemitones: -24, remaindingSemitones: 0 },
    { totalSemitones: -23, remaindingSemitones: -11 },
    { totalSemitones: -22, remaindingSemitones: -10 },
    { totalSemitones: -21, remaindingSemitones: -9 },
    { totalSemitones: -20, remaindingSemitones: -8 },
    { totalSemitones: -19, remaindingSemitones: -7 },
    { totalSemitones: -18, remaindingSemitones: -6 },
    { totalSemitones: -17, remaindingSemitones: -5 },
    { totalSemitones: -16, remaindingSemitones: -4 },
    { totalSemitones: -15, remaindingSemitones: -3 },
    { totalSemitones: -14, remaindingSemitones: -2 },
    { totalSemitones: -13, remaindingSemitones: -1 },
    { totalSemitones: -12, remaindingSemitones: 0 },
    { totalSemitones: -11, remaindingSemitones: -11 },
    { totalSemitones: -10, remaindingSemitones: -10 },
    { totalSemitones: -9, remaindingSemitones: -9 },
    { totalSemitones: -8, remaindingSemitones: -8 },
    { totalSemitones: -7, remaindingSemitones: -7 },
    { totalSemitones: -6, remaindingSemitones: -6 },
    { totalSemitones: -5, remaindingSemitones: -5 },
    { totalSemitones: -4, remaindingSemitones: -4 },
    { totalSemitones: -3, remaindingSemitones: -3 },
    { totalSemitones: -2, remaindingSemitones: -2 },
    { totalSemitones: -1, remaindingSemitones: -1 },
    { totalSemitones: 0, remaindingSemitones: 0 },
    { totalSemitones: 1, remaindingSemitones: 1 },
    { totalSemitones: 2, remaindingSemitones: 2 },
    { totalSemitones: 3, remaindingSemitones: 3 },
    { totalSemitones: 4, remaindingSemitones: 4 },
    { totalSemitones: 5, remaindingSemitones: 5 },
    { totalSemitones: 6, remaindingSemitones: 6 },
    { totalSemitones: 7, remaindingSemitones: 7 },
    { totalSemitones: 8, remaindingSemitones: 8 },
    { totalSemitones: 9, remaindingSemitones: 9 },
    { totalSemitones: 10, remaindingSemitones: 10 },
    { totalSemitones: 11, remaindingSemitones: 11 },
    { totalSemitones: 12, remaindingSemitones: 0 },
    { totalSemitones: 13, remaindingSemitones: 1 },
    { totalSemitones: 14, remaindingSemitones: 2 },
    { totalSemitones: 15, remaindingSemitones: 3 },
    { totalSemitones: 16, remaindingSemitones: 4 },
    { totalSemitones: 17, remaindingSemitones: 5 },
    { totalSemitones: 18, remaindingSemitones: 6 },
    { totalSemitones: 19, remaindingSemitones: 7 },
    { totalSemitones: 20, remaindingSemitones: 8 },
    { totalSemitones: 21, remaindingSemitones: 9 },
    { totalSemitones: 22, remaindingSemitones: 10 },
    { totalSemitones: 23, remaindingSemitones: 11 },
    { totalSemitones: 24, remaindingSemitones: 0 },
    { totalSemitones: 25, remaindingSemitones: 1 },
    { totalSemitones: 26, remaindingSemitones: 2 },
    { totalSemitones: 27, remaindingSemitones: 3 },
    { totalSemitones: 28, remaindingSemitones: 4 },
    { totalSemitones: 29, remaindingSemitones: 5 },
    { totalSemitones: 30, remaindingSemitones: 6 },
    { totalSemitones: 31, remaindingSemitones: 7 },
    { totalSemitones: 32, remaindingSemitones: 8 },
    { totalSemitones: 33, remaindingSemitones: 9 },
    { totalSemitones: 34, remaindingSemitones: 10 },
    { totalSemitones: 35, remaindingSemitones: 11 },
    { totalSemitones: 36, remaindingSemitones: 0 },
    { totalSemitones: 37, remaindingSemitones: 1 },
    { totalSemitones: 38, remaindingSemitones: 2 },
    { totalSemitones: 39, remaindingSemitones: 3 },
    { totalSemitones: 40, remaindingSemitones: 4 },
    { totalSemitones: 41, remaindingSemitones: 5 },
    { totalSemitones: 42, remaindingSemitones: 6 },
    { totalSemitones: 43, remaindingSemitones: 7 },
    { totalSemitones: 44, remaindingSemitones: 8 },
    { totalSemitones: 45, remaindingSemitones: 9 },
    { totalSemitones: 46, remaindingSemitones: 10 },
    { totalSemitones: 47, remaindingSemitones: 11 },
    { totalSemitones: 48, remaindingSemitones: 0 },
    { totalSemitones: 49, remaindingSemitones: 1 },
    { totalSemitones: 50, remaindingSemitones: 2 }
  ])(
    'A SemitoneSpan of $totalSemitones semitones should have $remaindingSemitones remainding semitones',
    d => expect(new SemitoneSpan(d.totalSemitones).remaindingSemitones).toBe(d.remaindingSemitones)
  );

  test.each<{ octaves: number, semitones: number, totalSemitones: number }>([
    { octaves: -4, semitones: -2, totalSemitones: -50 },
    { octaves: -4, semitones: -1, totalSemitones: -49 },
    { octaves: -4, semitones: 0, totalSemitones: -48 },
    { octaves: -3, semitones: -11, totalSemitones: -47 },
    { octaves: -3, semitones: -10, totalSemitones: -46 },
    { octaves: -3, semitones: -9, totalSemitones: -45 },
    { octaves: -3, semitones: -8, totalSemitones: -44 },
    { octaves: -3, semitones: -7, totalSemitones: -43 },
    { octaves: -3, semitones: -6, totalSemitones: -42 },
    { octaves: -3, semitones: -5, totalSemitones: -41 },
    { octaves: -3, semitones: -4, totalSemitones: -40 },
    { octaves: -3, semitones: -3, totalSemitones: -39 },
    { octaves: -3, semitones: -2, totalSemitones: -38 },
    { octaves: -3, semitones: -1, totalSemitones: -37 },
    { octaves: -3, semitones: 0, totalSemitones: -36 },
    { octaves: -2, semitones: -11, totalSemitones: -35 },
    { octaves: -2, semitones: -10, totalSemitones: -34 },
    { octaves: -2, semitones: -9, totalSemitones: -33 },
    { octaves: -2, semitones: -8, totalSemitones: -32 },
    { octaves: -2, semitones: -7, totalSemitones: -31 },
    { octaves: -2, semitones: -6, totalSemitones: -30 },
    { octaves: -2, semitones: -5, totalSemitones: -29 },
    { octaves: -2, semitones: -4, totalSemitones: -28 },
    { octaves: -2, semitones: -3, totalSemitones: -27 },
    { octaves: -2, semitones: -2, totalSemitones: -26 },
    { octaves: -2, semitones: -1, totalSemitones: -25 },
    { octaves: -2, semitones: 0, totalSemitones: -24 },
    { octaves: -1, semitones: -11, totalSemitones: -23 },
    { octaves: -1, semitones: -10, totalSemitones: -22 },
    { octaves: -1, semitones: -9, totalSemitones: -21 },
    { octaves: -1, semitones: -8, totalSemitones: -20 },
    { octaves: -1, semitones: -7, totalSemitones: -19 },
    { octaves: -1, semitones: -6, totalSemitones: -18 },
    { octaves: -1, semitones: -5, totalSemitones: -17 },
    { octaves: -1, semitones: -4, totalSemitones: -16 },
    { octaves: -1, semitones: -3, totalSemitones: -15 },
    { octaves: -1, semitones: -2, totalSemitones: -14 },
    { octaves: -1, semitones: -1, totalSemitones: -13 },
    { octaves: -1, semitones: 0, totalSemitones: -12 },
    { octaves: 0, semitones: -11, totalSemitones: -11 },
    { octaves: 0, semitones: -10, totalSemitones: -10 },
    { octaves: 0, semitones: -9, totalSemitones: -9 },
    { octaves: 0, semitones: -8, totalSemitones: -8 },
    { octaves: 0, semitones: -7, totalSemitones: -7 },
    { octaves: 0, semitones: -6, totalSemitones: -6 },
    { octaves: 0, semitones: -5, totalSemitones: -5 },
    { octaves: 0, semitones: -4, totalSemitones: -4 },
    { octaves: 0, semitones: -3, totalSemitones: -3 },
    { octaves: 0, semitones: -2, totalSemitones: -2 },
    { octaves: 0, semitones: -1, totalSemitones: -1 },
    { octaves: 0, semitones: 0, totalSemitones: 0 },
    { octaves: 0, semitones: 1, totalSemitones: 1 },
    { octaves: 0, semitones: 2, totalSemitones: 2 },
    { octaves: 0, semitones: 3, totalSemitones: 3 },
    { octaves: 0, semitones: 4, totalSemitones: 4 },
    { octaves: 0, semitones: 5, totalSemitones: 5 },
    { octaves: 0, semitones: 6, totalSemitones: 6 },
    { octaves: 0, semitones: 7, totalSemitones: 7 },
    { octaves: 0, semitones: 8, totalSemitones: 8 },
    { octaves: 0, semitones: 9, totalSemitones: 9 },
    { octaves: 0, semitones: 10, totalSemitones: 10 },
    { octaves: 0, semitones: 11, totalSemitones: 11 },
    { octaves: 1, semitones: 0, totalSemitones: 12 },
    { octaves: 1, semitones: 1, totalSemitones: 13 },
    { octaves: 1, semitones: 2, totalSemitones: 14 },
    { octaves: 1, semitones: 3, totalSemitones: 15 },
    { octaves: 1, semitones: 4, totalSemitones: 16 },
    { octaves: 1, semitones: 5, totalSemitones: 17 },
    { octaves: 1, semitones: 6, totalSemitones: 18 },
    { octaves: 1, semitones: 7, totalSemitones: 19 },
    { octaves: 1, semitones: 8, totalSemitones: 20 },
    { octaves: 1, semitones: 9, totalSemitones: 21 },
    { octaves: 1, semitones: 10, totalSemitones: 22 },
    { octaves: 1, semitones: 11, totalSemitones: 23 },
    { octaves: 2, semitones: 0, totalSemitones: 24 },
    { octaves: 2, semitones: 1, totalSemitones: 25 },
    { octaves: 2, semitones: 2, totalSemitones: 26 },
    { octaves: 2, semitones: 3, totalSemitones: 27 },
    { octaves: 2, semitones: 4, totalSemitones: 28 },
    { octaves: 2, semitones: 5, totalSemitones: 29 },
    { octaves: 2, semitones: 6, totalSemitones: 30 },
    { octaves: 2, semitones: 7, totalSemitones: 31 },
    { octaves: 2, semitones: 8, totalSemitones: 32 },
    { octaves: 2, semitones: 9, totalSemitones: 33 },
    { octaves: 2, semitones: 10, totalSemitones: 34 },
    { octaves: 2, semitones: 11, totalSemitones: 35 },
    { octaves: 3, semitones: 0, totalSemitones: 36 },
    { octaves: 3, semitones: 1, totalSemitones: 37 },
    { octaves: 3, semitones: 2, totalSemitones: 38 },
    { octaves: 3, semitones: 3, totalSemitones: 39 },
    { octaves: 3, semitones: 4, totalSemitones: 40 },
    { octaves: 3, semitones: 5, totalSemitones: 41 },
    { octaves: 3, semitones: 6, totalSemitones: 42 },
    { octaves: 3, semitones: 7, totalSemitones: 43 },
    { octaves: 3, semitones: 8, totalSemitones: 44 },
    { octaves: 3, semitones: 9, totalSemitones: 45 },
    { octaves: 3, semitones: 10, totalSemitones: 46 },
    { octaves: 3, semitones: 11, totalSemitones: 47 },
    { octaves: 4, semitones: 0, totalSemitones: 48 },
    { octaves: 4, semitones: 1, totalSemitones: 49 },
    { octaves: 4, semitones: 2, totalSemitones: 50 }
  ])(
    'A SemitoneSpan of $octaves octaves and $semitones semitones should span a total of $totalSemitones semitones',
    d => expect((new SemitoneSpan(d.octaves, d.semitones).totalSemitones)).toBe(d.totalSemitones)
  );
  
});